# frozen_string_literal: true

# Released under the MIT License.
# Copyright, 2016-2026, by Samuel Williams.

require "json"
require "fileutils"

module Protocol
	module Media
		module Data
			# Generates static indexes from the mime-types-data registry.
			class Generator
				# Load the currently installed mime-types-data registry.
				def self.load(destination)
					require "mime/types/data"
					
					path = File.join(MIME::Types::Data::PATH, "mime-types.json")
					new(JSON.parse(File.read(path)), destination)
				end
				
				def initialize(records, destination)
					@records = records.sort_by {|record| record.fetch("content-type")}
					@destination = destination
				end
				
				# Generate the Ruby and native indexes.
				def generate
					generate_ruby
					generate_gperf
				end
				
				private
				
				def extensions
					@extensions ||= @records.each_with_object(Hash.new {|hash, key| hash[key] = []}) do |record, extensions|
						record.fetch("extensions", []).each do |extension|
							extensions[extension] << record
						end
					end.transform_values do |records|
						records.min_by do |record|
							[record.fetch("sort-priority", 100), record["registered"] ? 0 : 1, record.fetch("content-type")]
						end.fetch("content-type")
					end
				end
				
				def record_values(record)
					[record.fetch("content-type"), record["encoding"], record["extensions"]]
				end
				
				def generate_ruby
					path = File.join(@destination, "lib/protocol/media/data/records.rb")
					FileUtils.mkdir_p(File.dirname(path))
					
					File.open(path, "w") do |output|
						output.puts <<~RUBY
							# frozen_string_literal: true
							
							# This file is generated by tasks/generator.rb.
							
							module Protocol
							\tmodule Media
							\t\tmodule Data
							\t\t\tRECORDS = {
						RUBY
						
						@records.each do |record|
							output.puts "\t\t\t\t#{record.fetch("content-type").dump} => #{record_values(record).inspect},"
						end
						
						output.puts "\t\t\t}.freeze"
						output.puts "\t\t\t"
						output.puts "\t\t\tEXTENSIONS = {"
						
						extensions.sort.each do |extension, name|
							output.puts "\t\t\t\t#{extension.dump} => #{name.dump},"
						end
						
						output.puts "\t\t\t}.freeze"
						output.puts "\t\tend"
						output.puts "\tend"
						output.puts "end"
					end
				end
				
				def generate_gperf
					extension_path = File.join(@destination, "ext/protocol/media/data/extensions.gperf")
					record_path = File.join(@destination, "ext/protocol/media/data/records.gperf")
					FileUtils.mkdir_p(File.dirname(extension_path))
					
					File.open(extension_path, "w") do |output|
						output.puts "%language=ANSI-C\n%readonly-tables\n%define slot-name extension\n%define hash-function-name extension_hash\n%define lookup-function-name lookup_extension\n%enum\n%switch=4"
						output.puts "struct ExtensionRecord { const char *extension; const char *name; };\n%%"
						extensions.sort.each {|extension, name| output.puts "#{extension}, #{name.dump}"}
					end
					
					File.open(record_path, "w") do |output|
						output.puts "%language=ANSI-C\n%readonly-tables\n%define slot-name name\n%define hash-function-name record_hash\n%define lookup-function-name lookup_record\n%enum\n%switch=4"
						output.puts "struct MediaTypeRecord { const char *name; const char *encoding; const char *extensions; };\n%%"
						@records.each do |record|
							encoding = record["encoding"]&.dump || "0"
							record_extensions = record["extensions"]&.join(" ")&.dump || "0"
							output.puts "#{record.fetch("content-type")}, #{encoding}, #{record_extensions}"
						end
					end
					
					system("gperf", "-CDt", extension_path, "--output-file", extension_path.sub(/\.gperf\z/, ".h"), exception: true)
					system("gperf", "-Ct", record_path, "--output-file", record_path.sub(/\.gperf\z/, ".h"), exception: true)
				end
			end
		end
	end
end
