# frozen_string_literal: true

# Released under the MIT License.
# Copyright, 2026, by Samuel Williams.

require "json"
require "fileutils"
require "open3"

module Protocol
	module Media
		module Registry
			# Generates static indexes from the mime-types-data registry.
			class Generator
				ADDITIONAL_EXTENSIONS = {
					"application/json" => ["map"],
				}.freeze
				
				# Load the currently installed mime-types-data registry.
				def self.load(destination)
					require "mime/types/data"
					
					path = File.join(MIME::Types::Data::PATH, "mime-types.json")
					new(JSON.parse(File.read(path)), destination)
				end
				
				def initialize(records, destination)
					@records = add_extensions(records).sort_by{|record| record.fetch("content-type")}
					@destination = destination
				end
				
				# Generate the Ruby and native indexes.
				def generate
					generate_ruby
					generate_gperf
				end
				
				private
				
				def add_extensions(records)
					remaining = ADDITIONAL_EXTENSIONS.dup
					
					updated = records.map do |record|
						if additions = remaining.delete(record.fetch("content-type"))
							extensions = (record.fetch("extensions", []) + additions).uniq
							record.merge("extensions" => extensions)
						else
							record
						end
					end
					
					unless remaining.empty?
						raise KeyError, "Could not find media types for additional extensions: #{remaining.keys.join(", ")}"
					end
					
					updated
				end
				
				def extension_priority(record, extension)
					priority = record.fetch("sort-priority", 0xff)
					preferred_extension = record["preferred-extension"] || record.fetch("extensions", []).first
					
					if extension == preferred_extension && (priority & 0b1000) != 0
						priority = (priority & 0b11110111) | 0b0111
					end
					
					[priority, record.fetch("content-type").downcase]
				end
				
				def extensions
					return @extensions if @extensions
					
					grouped = @records.each_with_object(Hash.new{|hash, key| hash[key] = []}) do |record, extensions|
						record.fetch("extensions", []).each do |extension|
							extensions[extension] << record
						end
					end
					
					@extensions = grouped.to_h do |extension, records|
						preferred = records.min_by{|record| extension_priority(record, extension)}
						[extension, preferred.fetch("content-type")]
					end
				end
				
				def record_values(record)
					[record.fetch("content-type"), record["encoding"], record["extensions"]]
				end
				
				def generate_ruby
					path = File.join(@destination, "lib/protocol/media/registry/records.rb")
					FileUtils.mkdir_p(File.dirname(path))
					
					File.open(path, "w") do |output|
						output.puts <<~RUBY
							# frozen_string_literal: true
							
							# Released under the MIT License.
							# Copyright, 2026, by Samuel Williams.
							
							# This file is generated by tasks/generator.rb.
							
							module Protocol
							\tmodule Media
							\t\tmodule Registry
							\t\t\tRECORDS = {
						RUBY
						
						@records.each do |record|
							output.puts "\t\t\t\t#{record.fetch("content-type").dump} => #{record_values(record).inspect},"
						end
						
						output.puts "\t\t\t}.freeze"
						output.puts "\t\t\t"
						output.puts "\t\t\tEXTENSIONS = {"
						
						extensions.sort.each do |extension, name|
							output.puts "\t\t\t\t#{extension.dump} => #{name.dump},"
						end
						
						output.puts "\t\t\t}.freeze"
						output.puts "\t\tend"
						output.puts "\tend"
						output.puts "end"
					end
				end
				
				def generate_gperf
					extension_path = File.join(@destination, "ext/protocol/media/registry/extensions.gperf")
					record_path = File.join(@destination, "ext/protocol/media/registry/records.gperf")
					FileUtils.mkdir_p(File.dirname(extension_path))
					
					File.open(extension_path, "w") do |output|
						output.puts "%{\n/* Released under the MIT License. */\n/* Copyright, 2026, by Samuel Williams. */\n%}"
						output.puts "%language=ANSI-C\n%readonly-tables\n%define slot-name extension\n%define hash-function-name extension_hash\n%define lookup-function-name lookup_extension\n%enum\n%switch=4"
						output.puts "struct ExtensionRecord { const char *extension; const char *name; };\n%%"
						extensions.sort.each{|extension, name| output.puts "#{extension}, #{name.dump}"}
					end
					
					File.open(record_path, "w") do |output|
						output.puts "%{\n/* Released under the MIT License. */\n/* Copyright, 2026, by Samuel Williams. */\n%}"
						output.puts "%language=ANSI-C\n%readonly-tables\n%define slot-name name\n%define hash-function-name record_hash\n%define lookup-function-name lookup_record\n%enum\n%switch=4"
						output.puts "struct MediaTypeRecord { const char *name; const char *encoding; const char *extensions; };\n%%"
						@records.each do |record|
							encoding = record["encoding"]&.dump || "0"
							record_extensions = record["extensions"]&.join(" ")&.dump || "0"
							output.puts "#{record.fetch("content-type")}, #{encoding}, #{record_extensions}"
						end
					end
					
					generate_gperf_header(extension_path, "-CDt")
					generate_gperf_header(record_path, "-Ct")
				end
				
				def generate_gperf_header(path, *arguments)
					output, error, status = Open3.capture3("gperf", *arguments, File.basename(path), chdir: File.dirname(path))
					
					unless status.success?
						raise "Could not generate #{path}: #{error}"
					end
					
					output.sub!(/^\/\* Command-line:.*\*\/\n/, "")
					File.write(path.sub(/\.gperf\z/, ".h"), output)
				end
			end
		end
	end
end
